In [1]:
import tensorflow as tf
import numpy as np
# We will enable eager execution in this notebook to be able to print tensors directly, usually we WON'T do this.
tf.enable_eager_execution()

### Important Trick
Press Tab for autofill.  
Press Ctrl+ (1x/2x/4x) Tab for different kinds of documentation.

In [2]:
complex_long_variable_name = 3

In [7]:
x = complex_long_variable_name
b = np.mean(x)

### What is a Tensor?

For our use it is sufficient to look at tensors as multidimensional arrays.  
A 0-dimensional tensor would be a scalar. Shape ().  
A 1-dimensional tensor would be a vector. Shape (n,).  
A 2-dimensional tensor would be a matrix. Shape (m,n).  
A 3-dimensional tensor is like "a cube with numbers". Shape (l,m,n).  
...

### Arithmetic Operators

In [4]:
# Arithmetic Operators are just like in numpy.

a = 3.0 * tf.ones(3) # (3, 3, 3)
b = -1.0 * tf.ones(3) # (-1, -1, -1)
c = tf.add(a,b)
print(c)
# c = tf.substract(a,b)
# c = tf.multiply(a, b)
# c = tf.divide(a,b)
# c = tf.mod(a,b)
# etc.

tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)


In [5]:
# You can also use the "normal" operators.

c = a + b
print(c)
# c = a-b
# c = a*b
# c = a/b
# c = a%b
# etc.

tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)


### Basic Math Functions

In [6]:
d = tf.exp(c)
print(d)
# d = tf.abs(a)
# d = tf.sqrt(a)
# d = tf.square(a)
# d = tf.sin(a)
# etc.

tf.Tensor([7.389056 7.389056 7.389056], shape=(3,), dtype=float32)


### Matrix Math Functions

In [9]:
M = tf.ones((3,3)) # 3x3 matrix filled with 1
print(M)
e = tf.norm(M)
print(e)
N = tf.matmul(M,M) # or M @ M 
print(N)
# N = tf.transpose(M)
# etc.

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]], shape=(3, 3), dtype=float32)


### Reduction

In [10]:
# Reduction operations reduce the dimensionality of a tensor.
m = tf.reduce_sum(M, axis=1)
print(M)
print(m)
n = tf.reduce_mean(N)
print(N)
print(n)
# n = tf.reduce_min(N)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor([3. 3. 3.], shape=(3,), dtype=float32)
tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]], shape=(3, 3), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
